[general]
import = [
  "~/.config/alacritty/themes/rose-pine.toml"
]

[terminal]
shell = "/usr/bin/tmux"

[env]
TERM = "xterm-256color"

[window]
startup_mode = "Windowed" # Windowed | Maximized | Fullscreen
decorations = "Full" # "Full" | "None" | "Transparent" | "Buttonless"
dimensions = { columns = 150, lines = 35 } # columns x axis, lines y axis
padding = { x = 5, y = 3}
blur = false
opacity = 1.0
dynamic_title = false
title = "Alacritty"

[font]
size =12.5

normal = { family = "Iosevka Nerd Font Mono",style =  "Regular" }
bold = { family = "Iosevka Nerd Font Mono", style = "Bold" }
italic = { family = "Iosevka Nerd Font Mono", style = "Italic" }
bold_italic = { family = "Iosevka Nerd Font Mono", style = "Bold Italic" }

# [keyboard]
# bindings = [
#     { key = "C", mods = "Control|Shift", chars = "\u0003" },
#     { key = "C", mods  = "Control",  action = "CopySelection" },
#     { key = "V", mods  = "Control",  action = "PasteSelection" },
# ]

[selection]
save_to_clipboard = false
