require("plugins.treesitter")
require("plugins.conform")
require("plugins.trouble")
require("plugins.mini")
-- require("plugins.rosepine")
require("plugins.catppuccin")
require("plugins.blink")
require("plugins.neotree")
require("plugins.wakatime")
require("plugins.cord")
require("plugins.mason")
require("plugins.autotag")

require("fidget").setup({})
