require("mason").setup()
require("mason-lspconfig").setup({
    ensure_installed = {
        "lua_ls",
        "gopls",
        "clangd",
        "svelte",
        "ruff",
        "ty",
        "ts_ls",
        "terraformls",
        "cssls",
        "ansiblels",
        "emmet_language_server",
        "sqls",
        "angularls",
        "dockerls",
        "docker_compose_language_service",
        "bashls",
        "rust_analyzer",
        "tailwindcss"
        -- "nginx_language_server"
    },
    automatic_enable = {
        "lua_ls",
        "gopls",
        "clangd",
        "svelte-language-server",
        "ruff",
        "ty",
        "ts_ls",
        "terraformls",
        "cssls",
        "emmet_language_server",
        "ansiblels",
        "sqls",
        "angularls",
        "dockerls",
        "docker_compose_language_service",
        "nginx_language_server",
        "bashls",
        "rust_analyzer",
        "tailwindcss"
        -- exclude = {},
    },
})
